import Head from 'next/head'
import React from 'react'
import Header from './Header'
import LeftAside from './LeftAside'
import RightAside from './RightAside'
import Footer from './Footer'

export default function CommonLayout({children}) {
  return (
    <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='container-fluid'>
      <Header />
    </div>
    <main className='row m-0 a_tbdr'>
        <LeftAside />
        { children }
        <RightAside />
    </main>
    <Footer />
  </div>
  )
}
